workflows:
  ios-cloudy-build:
    name: Cloudy iOS App
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      xcode: latest
      cocoapods: default
      
      vars:
        XCODE_WORKSPACE: "Cloudy.xcworkspace"
        XCODE_SCHEME: "Cloudy"
    
    scripts:
      - name: Show project info
        script: |
          echo "📱 === PROJET CLOUDY ==="
          echo "Workspace: $XCODE_WORKSPACE"
          echo "Scheme: $XCODE_SCHEME"
          echo ""
          echo "📂 === STRUCTURE DU PROJET ==="
          ls -la
      
      - name: Install CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            echo "📦 Installation des CocoaPods..."
            pod install
          else
            echo "ℹ️ Pas de Podfile trouvé, skip"
          fi
      
      - name: List available schemes
        script: |
          echo "🔍 === SCHEMES DISPONIBLES ==="
          xcodebuild -list -workspace "$XCODE_WORKSPACE"
      
      - name: Build archive
        script: |
          echo "🔨 === COMPILATION DE CLOUDY ==="
          
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath "$CM_BUILD_DIR/build/Cloudy.xcarchive" \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     archive
      
      - name: Create IPA
        script: |
          echo "📦 === CRÉATION DU .IPA ==="
          
          # Trouver l'app compilée
          APP_PATH=$(find "$CM_BUILD_DIR/build/Cloudy.xcarchive/Products/Applications" -name "*.app" -type d | head -n 1)
          
          if [ -z "$APP_PATH" ]; then
            echo "❌ App non trouvée"
            echo "Contenu de l'archive:"
            ls -R "$CM_BUILD_DIR/build/Cloudy.xcarchive"
            exit 1
          fi
          
          echo "✅ App trouvée: $APP_PATH"
          
          # Créer le .ipa
          mkdir -p Payload
          cp -r "$APP_PATH" Payload/
          zip -r Cloudy.ipa Payload
          
          # Déplacer dans output
          mkdir -p "$CM_BUILD_DIR/output"
          mv Cloudy.ipa "$CM_BUILD_DIR/output/"
          
          echo ""
          echo "✅ === IPA CRÉÉ ==="
          ls -lh "$CM_BUILD_DIR/output/Cloudy.ipa"
    
    artifacts:
      - output/*.ipa
      - build/Cloudy.xcarchive
    
    publishing:
      email:
        recipients:
          - ton-email@gmail.com  # ⬅️ CHANGE TON EMAIL ICI
        notify:
          success: true
          failure: true